[package]
name = "ds-emulator-mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.ds-emulator]
path = "../"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
swift-bridge = "0.1"
zstd = "0.13"
