[package]
name = "ds-emulator-wasm"
version = "0.1.0"
authors = ["Anne Castrillon"]
edition = "2021"

[lib]
path="src/lib.rs"
crate-type = ["cdylib"]

[dependencies.ds-emulator]
path = "../"

[dependencies]
wasm-bindgen = "0.2.93"
console_error_panic_hook = "0.1.7"